### ISSUE TITLE
stc("orange") returns #000000

### ISSUE THREAD

**Issue by gc159128** [Gustu/string-to-color#11]
Dependency for hex-rgb has been changed from 1.0.0(string-to-color@2.1.4) to 4.1.0(string-to-color@2.1.5 or higher).

In hex-rgb@4.1.0:

`hexRgb('#cd2222cc');`
`//=> {red: 205, green: 34, blue: 34, alpha: 0.8}`
 
`hexRgb('#cd2222cc', {format: 'array'});`
`//=> [205, 34, 34, 0.8]`

Stc code assumes the format as array, thus in index.js line 22:

`if (color) colors.push(hexRgb(trimStart(color, '#')));`

Should be replaced with:

`22    if (color) colors.push(hexRgb(trimStart(color, '#'), {format: 'array'}));`

as array is no longer the default result format in hex-rgb@4.1.0.

**Comment by Gustu** [comment]
Fixed by @psigns. Thanks!

**Comment by Gustu** [comment]
Fixed in v2.2.2
