### ISSUE TITLE
What is the algorithm that is being used to generate the color generation from a string?

### ISSUE THREAD

**Issue by TechAurelianMisc2** [Gustu/string-to-color#26]
Is it a hash of some kind?

**Comment by Gustu** [comment]
The `generateColor` function is an interesting algorithm that generates a hexadecimal color based on a given input text. It does this by combining two separate methods of generating a color: one based on the characters in the input text, and another based on color names found within the text. Here's a breakdown of the different steps it takes:

`Obtaining Colors from Words`: The function getColors(text) is called, which extracts color names from the input text using the colornames package and lodash.words. This color is then converted to its RGB representation with the hexRgb function.

`Mixing the Colors`: If any colors were found in the text, they are then averaged together with the `mixColors(colors)` function, creating a "mixed" color.

`Generating a Color from the Text`: Meanwhile, the function also generates a color based solely on the characters in the text. It does this by iterating through each character in the text, calculating an intermediate value based on the character's ASCII value, and then using this to generate a hexadecimal color code.

`Combining the Colors`: If a mixed color was generated from color names in the text, this color is then combined with the color generated from the characters in the text. The way this is done is by taking a weighted average of the two colors, with the color from the text being given a weight of `TEXT_WEIGHT` and the mixed color being given a weight of `MIXED_WEIGHT`.

`Return`: The function finally returns the hexadecimal representation of the resulting color.

Note that if no color names were found in the text, the function will simply return the color generated from the characters in the text.
