### ISSUE TITLE
TypeScript types declaration file

### ISSUE THREAD

**Issue by geopic** [Gustu/string-to-color#5]
If you want I can write a TypeScript types declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by Gustu** [comment]
Go ahead ;)

**Comment by geopic** [comment]
Alright, I'll get started on it now.

**Comment by cascornelissen** [comment]
@Gustu, any chance we can get this merged? 😅

**Comment by Gustu** [comment]
@cascornelissen done

**Comment by Gustu** [comment]
Released in v2.2.0

**Comment by Gustu** [comment]
Bumped to 2.2.1 - added types to package.json
